const S=(title,summary,points,exam,practice,keywords=[])=>({title,summary,points,exam,practice,keywords});
const D=(title,description,icon,topics)=>({title,description,icon,topics});

window.GASTRO_SUMMARIES = [
{
 id:"fundamentos", number:"01", title:"Fundamentos da Gastronomia", icon:"📚",
 description:"Bases conceituais da formação: organização profissional, cultura alimentar, ciência dos alimentos, técnica dietética, nutrição e análise sensorial.",
 theme:1,
 disciplines:[
 D("Introdução à Gastronomia","Conceitos iniciais da profissão, organização da cozinha e linguagem técnica.","🍴",[
  S("Brigada de cozinha e organização profissional","A brigada divide responsabilidades para que uma cozinha profissional funcione com clareza, velocidade e controle. Modelos clássicos organizam funções por praças, mas operações contemporâneas adaptam essa estrutura ao porte do negócio. Mais importante que decorar cargos é entender fluxo, responsabilidade, comunicação e cadeia de comando.",["Chef de cuisine coordena a operação e o padrão técnico.","Sous-chef apoia gestão, produção e serviço.","Chef de partie responde por uma praça ou área.","Commis e auxiliares executam tarefas sob supervisão."],"Em prova, diferencie cargo, função e estrutura de brigada; lembre que a organização varia conforme o tipo de operação.","Observe uma cozinha real e desenhe quem recebe, pré-prepara, cozinha, finaliza e libera cada prato.",["brigada","chef","praça","organização"]),
  S("Mise en place","Mise en place é a preparação organizada de tudo que será necessário antes da execução. Inclui leitura da receita, pesagem, higienização, cortes, separação de utensílios, pré-aquecimento de equipamentos e definição da sequência de trabalho. Um bom mise en place reduz interrupções e ajuda a manter padrão e segurança.",["Leia a receita integralmente antes de começar.","Separe ingredientes na quantidade exata.","Agrupe tarefas por tempo, equipamento e dependência.","Deixe bancada limpa e itens identificados."],"Questões costumam relacionar mise en place a eficiência, padronização, produtividade e prevenção de erros.","Antes de uma aula prática, transforme a receita em checklist de ingredientes, utensílios e etapas.",["mise en place","organização","produção"]),
  S("Equipamentos, utensílios e terminologia","A escolha correta de equipamentos e utensílios influencia produtividade, segurança e qualidade. Facas, panelas, processadores, fornos, balanças e termômetros possuem funções específicas. A terminologia culinária padroniza a comunicação entre profissionais e evita ambiguidades durante a produção.",["Use o equipamento de acordo com a função e capacidade.","Termômetros e balanças ajudam a padronizar resultados.","Facas exigem técnica, afiação e armazenamento seguros.","Vocabulário técnico melhora comunicação de equipe."],"Revise termos como saltear, suar, branquear, deglaçar, reduzir, napar e pochar.","Monte um glossário pessoal com termo, definição e um exemplo de uso.",["utensílios","equipamentos","terminologia"])
 ]),
 D("História e Cultura da Alimentação","Alimentação como fenômeno social, histórico e cultural.","🏺",[
  S("Alimentação, identidade e sociedade","Comer é uma prática biológica e cultural. Ingredientes, horários, modos de preparo e regras de consumo refletem território, religião, classe, memória e relações sociais. A Gastronomia estuda a comida não apenas como produto, mas como parte de sistemas de significado e identidade.",["Hábitos alimentares são aprendidos socialmente.","Comidas podem marcar pertencimento e memória.","Mudanças econômicas e tecnológicas alteram práticas alimentares.","Receitas carregam trajetórias históricas."],"Em questões discursivas, relacione alimento, cultura e contexto em vez de explicar pratos isoladamente.","Analise um prato de família e identifique origem, ocasião, técnica e significado.",["cultura","identidade","memória"]),
  S("Formação histórica da alimentação brasileira","A alimentação brasileira resulta do encontro, conflito e adaptação entre povos indígenas, populações africanas trazidas à força, colonizadores europeus e fluxos migratórios posteriores. Ingredientes locais, técnicas de conservação, agricultura, comércio e relações de poder formaram cozinhas regionais diversas.",["Mandioca, milho, pescados e frutas nativas têm papel central.","Contribuições africanas envolvem técnicas, ingredientes e modos de comer.","Influências europeias foram adaptadas às condições locais.","Migrações posteriores ampliaram repertórios regionais."],"Evite respostas que reduzam a formação da cozinha brasileira a três influências estáticas; destaque processos históricos e regionais.","Escolha uma preparação brasileira e pesquise origem de ingredientes e técnicas.",["Brasil","matrizes alimentares","história"]),
  S("Patrimônio, memória e tradições culinárias","Patrimônio alimentar inclui saberes, práticas, celebrações, ingredientes e modos de fazer reconhecidos por comunidades. Preservar não significa congelar uma receita no tempo; tradições mudam, mas mantêm vínculos com grupos, territórios e memórias coletivas.",["Patrimônio material e imaterial podem se relacionar.","Modo de fazer pode ser tão importante quanto o prato final.","Comunidade participa da atribuição de valor cultural.","Inovação pode coexistir com preservação."],"Diferencie patrimônio alimentar de simples popularidade comercial de um prato.","Registre uma técnica tradicional local e descreva quem a pratica, quando e por quê.",["patrimônio","tradição","memória"])
 ]),
 D("Ciência dos Alimentos","Transformações físicas e químicas que explicam textura, sabor e comportamento culinário.","🧪",[
  S("Água, proteínas e estrutura","A água participa de dissolução, transferência de calor e textura. Proteínas podem desnaturar e coagular com calor, acidez, agitação ou sais. Em ovos, carnes e laticínios, controlar intensidade e tempo é essencial para evitar estruturas excessivamente firmes ou perda de suculência.",["Desnaturação altera a estrutura da proteína.","Coagulação forma redes e muda textura.","Temperatura e pH influenciam velocidade e intensidade.","Perda de água costuma aumentar com cocção excessiva."],"Associe fenômenos a exemplos: ovo coagulado, carne firme, leite talhado e espuma proteica.","Compare um ovo cozido em diferentes tempos e registre textura e aparência.",["proteínas","coagulação","água"]),
  S("Carboidratos, amidos e açúcares","Amidos absorvem água e gelatinizam com aquecimento, aumentando viscosidade. Açúcares contribuem com doçura, estrutura, retenção de água e escurecimento. Caramelização é transformação térmica dos açúcares e não deve ser confundida com reação de Maillard.",["Gelatinização depende de água e calor.","Resfriamento pode favorecer retrogradação do amido.","Açúcar interfere em textura e conservação.","Caramelização e Maillard são fenômenos distintos."],"Questões frequentes pedem diferenças entre gelatinização, caramelização e Maillard.","Observe como um molho engrossa antes e depois de atingir temperatura de gelatinização.",["amido","gelatinização","açúcar"]),
  S("Lipídios, emulsões e transferência de sabor","Gorduras influenciam textura, sensação de boca, aroma e transferência de calor. Emulsões combinam fases normalmente imiscíveis, como óleo e água, por meio de agitação e, muitas vezes, emulsificantes. Temperatura e proporção alteram estabilidade.",["Maionese é exemplo clássico de emulsão.","Lecitina da gema atua como emulsificante.","Gorduras carregam compostos aromáticos lipossolúveis.","Excesso de calor pode quebrar emulsões."],"Saiba explicar por que uma emulsão separa e como proporção, temperatura e emulsificante interferem.","Prepare vinagrete simples e emulsão com mostarda e compare estabilidade.",["gordura","emulsão","lipídios"])
 ]),
 D("Técnica Dietética","Padronização, rendimento, fatores de correção e efeitos do preparo.","⚖️",[
  S("Pesos, medidas e fator de correção","Peso bruto é o alimento como adquirido; peso líquido é a parte pronta para uso após limpeza e seleção. O fator de correção relaciona os dois valores e ajuda a estimar compras e custos. Quanto maior a perda no pré-preparo, maior tende a ser o fator.",["FC = peso bruto ÷ peso líquido.","Perdas variam por ingrediente, qualidade e técnica.","Padronização de cortes reduz variação.","Registros reais melhoram previsões futuras."],"Espere cálculos de fator de correção, peso líquido e quantidade de compra.","Pese um vegetal antes e depois da limpeza e calcule o fator real.",["fator de correção","peso bruto","peso líquido"]),
  S("Rendimento, porcionamento e indicador de conversão","Rendimento mostra quanto a preparação produz depois das etapas de pré-preparo e cocção. Porcionamento transforma o rendimento total em unidades padronizadas. Indicadores de conversão ajudam a prever alterações de peso causadas pela cocção.",["Defina porção em massa, volume ou unidade.","Registre perdas de limpeza e cocção separadamente.","Rendimento influencia custo por porção.","Padronizar porções facilita produção e serviço."],"Cálculos podem misturar rendimento, número de porções e peso por porção.","Pese uma preparação pronta e divida pelo peso padrão desejado de cada porção.",["rendimento","porcionamento","conversão"]),
  S("Efeitos do preparo sobre cor, textura e nutrientes","Corte, calor, água, oxigênio, pH e tempo alteram alimentos. Cozinhar pode melhorar digestibilidade e segurança, mas também provocar perdas de nutrientes sensíveis. A técnica ideal depende do objetivo sensorial e nutricional da preparação.",["Cocção em excesso pode aumentar perdas e amolecimento.","Pigmentos vegetais respondem a pH e temperatura.","Métodos com pouca água podem reduzir perdas por lixiviação.","Segurança deve vir antes da preservação estética."],"Relacione método de cocção à textura, cor e retenção de nutrientes.","Compare vegetal cozido em água abundante e no vapor.",["técnica dietética","nutrientes","textura"])
 ]),
 D("Nutrição Aplicada à Gastronomia","Princípios nutricionais úteis para planejamento e adaptação de preparações.","🥗",[
  S("Macronutrientes e funções","Carboidratos são fonte importante de energia; proteínas participam de estruturas e funções metabólicas; lipídios concentram energia e integram membranas e hormônios. Na cozinha, suas propriedades químicas também determinam textura, estrutura, aroma e saciedade.",["Carboidratos incluem açúcares, amidos e fibras.","Proteínas fornecem aminoácidos.","Lipídios podem ser saturados ou insaturados.","Quantidade e contexto importam mais que classificações isoladas."],"Associe nutriente, função corporal e comportamento culinário.","Analise um prato e identifique principais fontes de carboidrato, proteína e gordura.",["macronutrientes","proteínas","carboidratos","lipídios"]),
  S("Micronutrientes, fibras e diversidade alimentar","Vitaminas e minerais atuam em múltiplos processos metabólicos. Fibras contribuem para funcionamento intestinal, saciedade e características físicas dos alimentos. Uma alimentação variada tende a ampliar a diversidade de nutrientes e compostos bioativos.",["Vitaminas podem ser hidrossolúveis ou lipossolúveis.","Minerais não são destruídos pelo calor, mas podem migrar para líquidos.","Fibras têm diferentes propriedades tecnológicas e fisiológicas.","Variedade de cores não substitui avaliação nutricional, mas é um recurso prático."],"Evite afirmar que todo cozimento 'destrói nutrientes'; explique que os efeitos dependem do nutriente e do método.","Planeje uma preparação com vegetais de diferentes grupos e técnicas.",["vitaminas","minerais","fibras"]),
  S("Planejamento de refeições e adaptações","Planejar refeições envolve equilíbrio entre sabor, adequação nutricional, cultura, custo, disponibilidade e preferências. Restrições alimentares exigem substituições tecnicamente coerentes e prevenção de riscos, especialmente em casos de alergia.",["Substituição deve preservar função culinária, não só ingrediente.","Considere densidade nutricional e tamanho de porção.","Restrições médicas precisam de orientação profissional adequada.","Alergia exige controle de contato cruzado."],"Diferencie adaptação por preferência, intolerância e alergia.","Escolha uma receita e proponha adaptação explicando o papel do ingrediente substituído.",["planejamento","restrições","substituições"])
 ]),
 D("Análise Sensorial","Avaliação sistemática de aparência, aroma, sabor, textura e aceitação.","👃",[
  S("Percepção sensorial dos alimentos","A experiência de comer integra visão, olfato, paladar, tato, audição e expectativas. Sabor é uma percepção complexa que combina gostos básicos, aromas retronasais e sensações trigeminais, como ardor e frescor.",["Aroma influencia fortemente percepção de sabor.","Textura é percebida por boca e mãos.","Cor e apresentação criam expectativas.","Temperatura modifica aroma, doçura e textura."],"Diferencie gosto, aroma e sabor.","Experimente o mesmo alimento com o nariz livre e depois obstruído e compare.",["sensorial","aroma","sabor"]),
  S("Testes discriminativos, descritivos e afetivos","Testes sensoriais respondem a perguntas diferentes. Discriminativos verificam se amostras diferem; descritivos caracterizam atributos e intensidade; afetivos medem aceitação ou preferência de consumidores.",["Teste triangular é discriminativo.","Análise descritiva exige painel treinado.","Teste hedônico é afetivo.","Método deve ser escolhido conforme o objetivo."],"Questões costumam apresentar um objetivo e pedir o tipo de teste adequado.","Para comparar duas receitas, escreva primeiro qual pergunta você quer responder.",["teste triangular","hedônico","descritivo"]),
  S("Condições de teste e controle de viés","Amostras devem ser codificadas, servidas em condições controladas e apresentadas de forma que a ordem não favoreça uma resposta. Ambiente, iluminação, temperatura, quantidade e treinamento interferem nos resultados.",["Códigos cegos reduzem influência de marcas.","Randomização ajuda a controlar ordem.","Água pode ser usada para limpeza de palato, conforme o teste.","Instruções precisam ser padronizadas."],"Saiba identificar fontes de viés experimental em testes sensoriais.","Monte uma ficha simples de avaliação com atributos claros e escala definida.",["viés","painel","teste sensorial"])
 ])
]
},
{
 id:"tecnicas", number:"02", title:"Técnicas de Cozinha", icon:"🔪",
 description:"Domínio técnico de cortes, fundos, molhos, cocções, cozinha fria, proteínas, vegetais, cereais e leguminosas.",
 theme:2,
 disciplines:[
 D("Habilidades Básicas de Cozinha","Fundamentos práticos que sustentam a produção profissional.","🔪",[
  S("Cortes clássicos e padronização","Cortes regulares favorecem apresentação e cocção uniforme. Julienne produz tiras finas; brunoise, cubos pequenos; batonnet, bastões; chiffonade, tiras de folhas. A nomenclatura pode variar entre escolas, mas a lógica de padronização permanece.",["Use faca afiada e tábua estável.","Uniformidade é mais importante que velocidade.","Aparas podem ser destinadas a fundos quando adequadas.","Cortes devem respeitar uso final do ingrediente."],"Reconheça formatos e explique por que tamanho interfere na cocção.","Treine três cortes no mesmo vegetal e compare o tempo de cocção.",["cortes","julienne","brunoise"]),
  S("Fundos, caldos e bases aromáticas","Fundos extraem sabor de ossos, aparas, vegetais e aromáticos em líquido. Fundos claros evitam forte douramento; fundos escuros usam tostagem para desenvolver sabor. Fumets, caldos e essências seguem objetivos específicos.",["Mirepoix é uma combinação aromática de vegetais.","Fervura agressiva pode aumentar turvação.","Tempo excessivo pode extrair sabores indesejáveis.","Coar e resfriar corretamente é parte do processo."],"Diferencie fundo claro, fundo escuro e fumet.","Prepare um fundo vegetal e registre proporção, tempo e rendimento.",["fundos","caldos","mirepoix"]),
  S("Molhos e espessantes básicos","Molhos podem ser estruturados por redução, roux, amidos, emulsões ou purês. O roux combina farinha e gordura e precisa de cocção adequada. Emulsões exigem proporção, temperatura e agitação coerentes.",["Roux branco, claro e escuro diferem pelo tempo de cocção.","Slurry mistura amido com líquido frio antes de aquecer.","Redução concentra sabor junto com consistência.","Finalização deve ajustar sal, acidez e textura."],"Associe espessante ao resultado desejado: opacidade, brilho, sabor e estabilidade.","Faça o mesmo molho com roux e com amido e compare textura.",["molhos","roux","espessantes"])
 ]),
 D("Cozinha Quente","Métodos de cocção e controle de calor em preparações salgadas.","🔥",[
  S("Calor seco, úmido e misto","Métodos secos usam ar quente, gordura ou superfícies sem grande quantidade de líquido; métodos úmidos utilizam água ou vapor; métodos mistos combinam douramento e cocção com líquido. Escolher o método depende da estrutura do alimento e do resultado desejado.",["Assar, grelhar e saltear são secos.","Pochar, ferver e vapor são úmidos.","Brasear e ensopar combinam técnicas.","Tamanho da peça altera tempo e transferência de calor."],"Classifique métodos e justifique qual seria adequado para cortes macios ou ricos em colágeno.","Escolha três ingredientes e proponha um método de cocção para cada um.",["cocção","calor seco","calor úmido"]),
  S("Reação de Maillard e desenvolvimento de sabor","Maillard envolve reações entre compostos carbonílicos e grupos amino durante o aquecimento, produzindo cor e aromas complexos. Superfície muito úmida dificulta temperaturas de douramento porque a evaporação da água consome energia.",["Secar a superfície favorece douramento.","Maillard não é sinônimo de caramelização.","pH, temperatura e composição influenciam o processo.","Douramento adequado não significa queimar."],"Explique por que panela lotada pode reduzir douramento.","Sele a mesma proteína em panela cheia e em lotes menores e compare.",["Maillard","douramento","sabor"]),
  S("Controle de ponto, descanso e suculência","O ponto de cocção depende do alimento, temperatura interna, textura e preferência. Em carnes, o calor residual continua a agir após retirar da fonte. Descanso pode reduzir perda imediata de líquidos durante o corte.",["Use termômetro quando precisão for importante.","Espessura altera curva de aquecimento.","Calor residual precisa entrar no planejamento.","Segurança microbiológica deve orientar limites mínimos quando aplicável."],"Questões podem relacionar ponto, espessura, temperatura e descanso.","Meça a temperatura de uma peça imediatamente e após alguns minutos de descanso.",["ponto","temperatura","descanso"])
 ]),
 D("Garde Manger e Cozinha Fria","Preparações frias, saladas, emulsões, terrines e organização de buffet.","🥬",[
  S("Princípios da cozinha fria","Cozinha fria exige controle rigoroso de higiene porque muitas preparações não recebem cocção final antes do consumo. Textura, frescor, temperatura e montagem são centrais em saladas, entradas, canapés e buffets.",["Mantenha ingredientes refrigerados quando necessário.","Evite cruzamento entre crus e prontos.","Prepare folhas próximas ao serviço para preservar textura.","Molhos podem ser adicionados apenas no momento adequado."],"Relacione cozinha fria a maior dependência de higiene e controle de tempo/temperatura.","Monte um fluxo seguro para produzir salada com proteína cozida.",["garde manger","cozinha fria","saladas"]),
  S("Emulsões frias e vinagretes","Vinagretes são dispersões temporárias de óleo e fase aquosa; mostarda e outros componentes podem ajudar na estabilização. Maioneses são emulsões mais estáveis com auxílio de emulsificantes presentes na gema.",["Adicionar óleo gradualmente facilita emulsificação.","Temperaturas muito diferentes podem desestabilizar.","Acidez, sal e doçura precisam de equilíbrio.","Textura deve combinar com o ingrediente servido."],"Explique o papel da gema e da agitação na maionese.","Compare vinagrete simples com um preparado com mostarda.",["vinagrete","maionese","emulsão"]),
  S("Terrines, patês e montagem fria","Preparações moldadas exigem controle de textura, proporção de gordura, temperatura e compactação. A apresentação fria valoriza cortes limpos, contraste, proporção e facilidade de serviço.",["Resfriamento adequado ajuda a fixar estrutura.","Facas limpas produzem cortes mais definidos.","Decoração deve ser comestível e funcional.","Rendimento precisa ser calculado antes do serviço."],"Identifique fatores que determinam estabilidade e apresentação de uma terrine.","Planeje uma entrada fria considerando porção, cor, textura e temperatura.",["terrine","patê","montagem"])
 ]),
 D("Carnes e Aves","Estrutura muscular, cortes, métodos de cocção e aproveitamento.","🥩",[
  S("Estrutura muscular, colágeno e maciez","Músculo contém fibras, água, proteínas e tecido conjuntivo. Cortes muito solicitados pelo animal tendem a apresentar mais tecido conjuntivo e podem se beneficiar de cocção lenta e úmida. Cortes naturalmente macios aceitam métodos rápidos e secos.",["Colágeno pode converter-se em gelatina com tempo e umidade.","Marmoreio influencia sabor e sensação de suculência.","Corte transversal às fibras reduz resistência na mastigação.","Método precisa respeitar características do corte."],"Relacione corte rico em colágeno a braseado e corte macio a grelha ou sauté.","Compare duas peças de características diferentes e proponha métodos.",["carnes","colágeno","maciez"]),
  S("Selagem, cocção e descanso","Selar desenvolve cor e sabor; não cria uma barreira impermeável. A perda de água é influenciada por temperatura, tempo, estrutura e corte. Descanso após cocção pode ajudar a equilibrar distribuição de calor e reduzir perda ao fatiar.",["Não repita o mito de 'selar para fechar os poros'.","Superfície seca favorece Maillard.","Panela precisa ter energia térmica suficiente.","Fatiar contra as fibras melhora percepção de maciez."],"Questões de técnica costumam explorar o mito da selagem.","Faça uma ficha de observação com cor, suculência e textura em diferentes tempos.",["selagem","carne","descanso"]),
  S("Aves: cortes, segurança e aplicações","Aves permitem aproveitamento de peito, coxas, sobrecoxas, asas, carcaça e miúdos apropriados. Peito é mais magro e pode ressecar rapidamente; pernas têm mais tecido conjuntivo e toleram cocções mais longas.",["Carcaças podem formar fundos.","Separar cru de alimentos prontos é essencial.","Temperatura interna deve ser controlada conforme procedimento seguro.","Marinadas aromatizam, mas não substituem cocção segura."],"Relacione anatomia da ave ao método de cocção.","Desosse uma ave sob supervisão e registre rendimento de cada parte.",["aves","frango","segurança"])
 ]),
 D("Pescados e Frutos do Mar","Frescor, limpeza, cortes e cocções delicadas.","🐟",[
  S("Avaliação de frescor e conservação","Frescor de pescados é avaliado por aroma, firmeza, brilho, integridade e condições de conservação. Indicadores específicos variam por espécie e apresentação. Cadeia fria e procedência são fundamentais.",["Aroma deve ser característico, não pútrido.","Carne deve apresentar estrutura compatível com frescor.","Gelo e refrigeração precisam ser higienicamente controlados.","Compra depende de fornecedor confiável."],"Não use um único sinal como critério absoluto; combine observações.","Compare fichas de recebimento para peixe inteiro e filé.",["pescados","frescor","cadeia fria"]),
  S("Limpeza, filetagem e rendimento","Escamar, eviscerar, retirar pele e filetar geram perdas distintas. Rendimento depende da espécie, tamanho, técnica e finalidade. Cabeças e espinhas adequadas podem ser aproveitadas em fumets.",["Faca flexível auxilia filetagem.","Trabalhe sobre superfície limpa e fria.","Registre peso bruto e peso líquido.","Aparas só devem ser aproveitadas quando próprias e seguras."],"Cálculos de rendimento podem aparecer junto a fator de correção.","Pese o peixe antes e depois da limpeza para calcular rendimento.",["filetagem","rendimento","peixe"]),
  S("Cocção de peixes e frutos do mar","Pescados possuem proteínas que coagulam rapidamente e, em geral, exigem atenção para evitar ressecamento. Grelhar, assar, pochar, cozinhar no vapor e saltear são escolhas possíveis conforme espessura e espécie.",["Peças finas cozinham rapidamente.","Mariscos e crustáceos também exigem controle de tempo.","Molhos devem complementar sem mascarar frescor.","Temperatura e espessura determinam tempo real."],"Explique por que peixes delicados podem perder textura com cocção prolongada.","Teste duas técnicas no mesmo pescado e compare perda de massa.",["cocção","peixes","frutos do mar"])
 ]),
 D("Vegetais, Cereais e Leguminosas","Comportamento de ingredientes vegetais e bases amiláceas.","🥕",[
  S("Pigmentos, textura e cocção de vegetais","Clorofilas, carotenoides, antocianinas e outros pigmentos reagem de formas diferentes ao calor e ao pH. Textura depende de parede celular, água e tempo. Cocção curta pode preservar crocância, enquanto cocção longa favorece maciez.",["Vegetais verdes podem perder vivacidade com cocção prolongada.","Ácidos e bases alteram alguns pigmentos.","Branqueamento combina cocção breve e resfriamento rápido.","Tamanho do corte afeta velocidade de cocção."],"Relacione pigmento, pH e cor sem generalizações excessivas.","Cozinhe o mesmo vegetal em tempos diferentes e compare cor e textura.",["vegetais","pigmentos","branqueamento"]),
  S("Arroz, risotos e outros cereais","Cereais concentram amido e apresentam comportamentos distintos conforme variedade e método. No risoto, a adição gradual de líquido e agitação favorecem liberação de amido e textura cremosa sem transformar os grãos em purê.",["Variedade do arroz influencia absorção e textura.","Lavagem pode ser desejada ou evitada conforme preparação.","Caldo precisa estar adequado ao perfil do prato.","Repouso e finalização interferem na textura."],"Diferencie técnica de arroz soltinho e risoto.","Prepare dois tipos de arroz seguindo métodos diferentes.",["arroz","cereais","risoto"]),
  S("Leguminosas: hidratação, cocção e textura","Feijões, lentilhas, grão-de-bico e ervilhas secas possuem estruturas que exigem hidratação e cocção apropriadas. Tempo varia por espécie, idade do grão e condições de armazenamento.",["Remolho pode reduzir tempo de cocção em várias leguminosas.","Ácidos adicionados cedo podem retardar amolecimento em alguns casos.","Panela de pressão reduz tempo.","Caldo de cocção pode integrar a preparação."],"Questões podem explorar diferença entre cereal e leguminosa e fatores que afetam amolecimento.","Compare lentilha e grão-de-bico quanto a remolho, tempo e textura.",["leguminosas","feijão","cereais"])
 ])
]
},
{
 id:"panificacao-confeitaria", number:"03", title:"Panificação, Confeitaria e Bebidas", icon:"🥐",
 description:"Fermentação, massas, confeitaria, chocolate, sobremesas, bebidas e harmonização.",
 theme:3,
 disciplines:[
 D("Panificação","Estrutura de massas, fermentação, porcentagem do padeiro e forno.","🍞",[
  S("Glúten, hidratação e desenvolvimento de massa","Na farinha de trigo, proteínas formam rede de glúten quando hidratadas e trabalhadas. Essa rede retém gases e cria estrutura. Hidratação, sova, descanso, gordura, açúcar e acidez alteram comportamento da massa.",["Mais água tende a aumentar extensibilidade, dentro de limites.","Sova organiza e desenvolve a rede.","Descansos permitem relaxamento e redistribuição de água.","Farinha e processo precisam ser avaliados juntos."],"Explique a função do glúten e como descanso interfere na massa.","Faça teste de janela em diferentes momentos da sova.",["glúten","hidratação","sova"]),
  S("Fermentação e desenvolvimento de sabor","Leveduras metabolizam açúcares e produzem dióxido de carbono e compostos aromáticos. Tempo, temperatura, inoculação e formulação controlam velocidade. Fermentação longa pode ampliar complexidade, mas excesso enfraquece estrutura.",["Temperatura acelera ou desacelera atividade.","Sal influencia sabor e fermentação.","Açúcar e gordura podem tornar massas mais exigentes.","Ponto deve ser avaliado por volume e estrutura, não só relógio."],"Diferencie fermentação, crescimento e maturação de sabor.","Fermente porções iguais em temperaturas diferentes e compare.",["fermentação","levedura","pão"]),
  S("Porcentagem do padeiro e escalonamento","Na porcentagem do padeiro, a massa de farinha é 100% e cada ingrediente é expresso em relação a ela. O sistema facilita comparação, hidratação e aumento ou redução de fórmulas.",["Farinha = 100%.","Água ÷ farinha × 100 = hidratação.","Sal costuma aparecer em pequenas porcentagens.","Escalonamento mantém as proporções."],"Resolva exercícios com hidratação e conversão de fórmula para nova quantidade de farinha.","Pegue uma receita caseira e converta todos os ingredientes em porcentagem.",["porcentagem do padeiro","fórmula","hidratação"])
 ]),
 D("Confeitaria","Massas, cremes, merengues e precisão de processo.","🍰",[
  S("Cremes básicos e espessamento","Cremes podem ser espessados por gema, amido, chocolate, gelatina ou redução. Crème anglaise depende de coagulação controlada da gema; crème pâtissière combina gemas e amido, tornando-se mais espesso e estável para recheios.",["Temperatura excessiva pode coagular gema de forma irregular.","Amido precisa de calor suficiente para gelatinizar.","Resfriamento rápido ajuda segurança e textura.","Filme em contato reduz formação de película."],"Diferencie anglaise e pâtissière pela estrutura e aplicação.","Prepare um creme e registre temperatura, textura quente e textura fria.",["cremes","confeitaria","espessamento"]),
  S("Merengues francês, suíço e italiano","Merengues são espumas de claras estabilizadas com açúcar. O francês recebe açúcar durante o batimento; o suíço aquece claras e açúcar antes de bater; o italiano incorpora calda quente em claras batidas. Métodos geram estabilidade e usos diferentes.",["Gordura prejudica formação da espuma.","Açúcar estabiliza e aumenta viscosidade.","Método italiano costuma gerar alta estabilidade.","Utensílios precisam estar limpos e secos."],"Compare os três métodos, não apenas ingredientes.","Prepare dois métodos e observe brilho, firmeza e comportamento ao repouso.",["merengue","claras","açúcar"]),
  S("Massas de confeitaria","Massas quebradiças, batidas, folhadas e cozidas dependem de proporções e desenvolvimento estrutural diferentes. Em pâte brisée e sablée, controlar glúten evita rigidez; em pâte à choux, a expansão de vapor cria cavidade interna.",["Frio ajuda massas ricas em gordura.","Mistura excessiva pode desenvolver glúten.","Folhados dependem de camadas de massa e gordura.","Pâte à choux precisa secar parcialmente antes dos ovos."],"Associe tipo de massa à técnica de estruturação.","Compare sablée e brisée quanto a gordura, mistura e textura.",["massas","sablée","folhado"])
 ]),
 D("Chocolateria","Cacau, cristalização, temperagem e preparações com chocolate.","🍫",[
  S("Composição do chocolate e tipos","Chocolate combina sólidos de cacau, manteiga de cacau, açúcar e, em alguns tipos, componentes lácteos. Proporções alteram sabor, fluidez e aplicação. Coberturas fracionadas usam gorduras diferentes e não se comportam como chocolate puro.",["Maior teor de cacau não define sozinho qualidade.","Manteiga de cacau determina parte importante da cristalização.","Chocolate branco não possui sólidos não gordurosos de cacau.","Leia a composição antes de escolher uma técnica."],"Diferencie chocolate, cobertura e chocolate branco por composição e comportamento.","Compare rótulos de três produtos e relacione ingredientes ao uso culinário.",["chocolate","cacau","manteiga de cacau"]),
  S("Temperagem e cristalização","Temperagem controla a formação de cristais estáveis da manteiga de cacau por aquecimento, resfriamento e retorno à temperatura de trabalho. Uma boa cristalização favorece brilho, contração, quebra limpa e resistência relativa ao toque.",["Faixas de temperatura variam conforme o tipo de chocolate.","Umidade é inimiga de chocolate derretido.","Cristais estáveis podem ser induzidos por tablagem ou semeadura.","Ambiente muito quente dificulta cristalização."],"Explique o objetivo da curva de temperagem, não apenas números.","Tempere pequena quantidade por semeadura e faça teste de cristalização.",["temperagem","cristalização","chocolate"]),
  S("Ganache, emulsões e recheios","Ganache é uma emulsão de chocolate e fase aquosa, geralmente creme. A proporção determina fluidez e aplicação: cobertura, recheio, trufa ou montagem. Técnica de emulsificação influencia brilho e textura.",["Picar chocolate facilita fusão uniforme.","Adicionar líquido quente gradualmente ajuda emulsão.","Misturar do centro para fora favorece núcleo elástico.","Ingredientes extras alteram atividade de água e estabilidade."],"Relacionar proporção a uso é mais importante que decorar uma fórmula única.","Faça ganaches com proporções diferentes e compare firmeza após resfriamento.",["ganache","emulsão","recheios"])
 ]),
 D("Sobremesas e Finalização","Equilíbrio, texturas, temperaturas e empratamento de sobremesas.","🍨",[
  S("Construção de uma sobremesa equilibrada","Uma sobremesa pode combinar doce, ácido, amargo, salgado, crocante, cremoso, quente e frio. Nem todos os elementos precisam aparecer ao mesmo tempo; a composição deve ter lógica, foco e porção adequada.",["Acidez pode equilibrar doçura.","Sal em pequena quantidade pode realçar sabores.","Contraste de textura aumenta interesse.","Elementos devem ter função sensorial."],"Ao analisar uma sobremesa, explique equilíbrio e função de cada componente.","Desenhe uma sobremesa com base cremosa, elemento crocante e componente ácido.",["sobremesa","equilíbrio","textura"]),
  S("Gelados, sorvetes e cristalização","Sobremesas congeladas dependem do equilíbrio entre água, açúcares, gorduras, sólidos e incorporação de ar. Cristais de gelo pequenos geram textura mais fina; congelamento lento e oscilações de temperatura podem aumentar cristais.",["Açúcar reduz o ponto de congelamento.","Gordura e sólidos afetam corpo e cremosidade.","Agitação durante congelamento controla cristalização.","Armazenamento estável preserva textura."],"Entenda fatores de textura em vez de tratar sorvete como simples congelamento.","Compare textura de uma base congelada parada e outra processada com agitação.",["sorvete","gelados","cristais"]),
  S("Empratamento de sobremesas","O empratamento deve considerar ponto focal, proporção, contraste, volume, cor e facilidade de consumo. Molhos e elementos decorativos precisam estar coerentes com sabor e textura.",["Evite decoração não comestível ou sem função.","Prato muito grande pode reduzir percepção de porção.","Altura cria dinamismo, mas precisa ser estável.","Temperatura de serviço faz parte da montagem."],"Questões podem pedir princípios de composição visual e funcionalidade.","Fotografe duas montagens do mesmo doce e compare leitura visual.",["empratamento","sobremesas","finalização"])
 ]),
 D("Bebidas e Cafeteria","Café, chá, bebidas não alcoólicas e princípios de serviço.","☕",[
  S("Extração de café","Extração depende da proporção café/água, moagem, tempo, temperatura, método e qualidade da água. Subextração pode gerar acidez agressiva e pouca doçura; superextração pode aumentar amargor e adstringência.",["Moagem fina aumenta área de contato.","Tempo precisa combinar com o método.","Água influencia minerais e percepção.","Dose e rendimento devem ser registrados."],"Explique como mudar moagem altera extração.","Prepare a mesma dose com duas moagens e compare sensorialmente.",["café","extração","moagem"]),
  S("Chás e infusões","Camellia sinensis origina chás brancos, verdes, oolongs, pretos e outros, conforme processamento. Infusões de ervas e frutas não são tecnicamente chá dessa planta. Temperatura e tempo influenciam extração de aroma, taninos e amargor.",["Folha, processamento e origem afetam perfil.","Água muito quente pode acentuar amargor em alguns chás.","Tempo excessivo aumenta extração de compostos adstringentes.","Serviço deve considerar temperatura final."],"Diferencie chá verdadeiro e infusão.","Faça uma mesma folha em dois tempos de infusão e compare.",["chá","infusão","bebidas"]),
  S("Bebidas não alcoólicas e serviço","Sucos, sodas, xaropes, shrubs, mocktails e bebidas fermentadas não alcoólicas podem construir equilíbrio com acidez, doçura, amargor, aroma e gás. Padronização de receita e gelo é importante para consistência.",["Gelo é ingrediente e altera diluição.","Xaropes padronizam doçura.","Acidez pode vir de cítricos ou outras fontes.","Guarnição deve ser segura e coerente."],"Analise bebida por equilíbrio, não apenas decoração.","Crie uma bebida sem álcool e registre proporção, diluição e custo.",["mocktail","bebidas","serviço"])
 ]),
 D("Enologia e Harmonização","Noções de vinho, serviço e relação entre bebida e alimento.","🍷",[
  S("Estrutura básica do vinho","Vinhos podem apresentar diferentes níveis de acidez, álcool, açúcar, tanino, corpo e intensidade aromática. Uva, clima, solo, vinificação e envelhecimento interagem na formação do perfil.",["Acidez traz frescor e influencia harmonização.","Tanino é associado principalmente a estrutura de tintos.","Açúcar residual altera percepção de doçura.","Álcool contribui para corpo e calor."],"Aprenda a descrever estrutura antes de decorar rótulos e regiões.","Prove bebidas com diferentes níveis de acidez e registre percepção.",["vinho","acidez","tanino"]),
  S("Serviço e conservação do vinho","Temperatura, taça, abertura, aeração e conservação após abertura influenciam a experiência. Regras de serviço devem ser aplicadas com finalidade, e não como ritual rígido.",["Temperatura muito alta aumenta percepção alcoólica.","Temperatura baixa pode reduzir expressão aromática.","Taça limpa e sem odores é fundamental.","Oxigênio pode abrir aromas, mas também oxidar."],"Explique o efeito da temperatura na percepção.","Sirva a mesma bebida em temperaturas diferentes e compare aroma e corpo.",["serviço","vinho","temperatura"]),
  S("Princípios de harmonização","Harmonização pode buscar semelhança, contraste ou limpeza do paladar. Intensidade, gordura, acidez, doçura, sal, amargor, picância e aroma são variáveis importantes.",["Bebida e prato precisam ter intensidades compatíveis.","Acidez pode equilibrar gordura.","Doçura da bebida deve acompanhar sobremesas muito doces.","Picância e álcool alto podem aumentar sensação de calor."],"Justifique harmonização usando elementos sensoriais, não apenas regras decoradas.","Escolha um prato e proponha duas bebidas com lógicas diferentes.",["harmonização","bebidas","sensorial"])
 ])
]
},
{
 id:"cozinhas-mundo", number:"04", title:"Cozinhas do Brasil e do Mundo", icon:"🌎",
 description:"Cozinhas regionais, tradições clássicas e repertórios internacionais estudados na formação gastronômica.",
 theme:4,
 disciplines:[
 D("Cozinha Brasileira","Ingredientes, técnicas e formação histórica das cozinhas brasileiras.","🇧🇷",[
  S("Diversidade regional e território","Não existe uma única cozinha brasileira. Biomas, clima, agricultura, rios, litoral, migrações e história formam repertórios próprios. Estudar regiões exige relacionar ingredientes e pratos a contextos de produção e consumo.",["Amazônia valoriza grande diversidade de peixes e ingredientes florestais.","Nordeste reúne múltiplas cozinhas litorâneas e sertanejas.","Centro-Oeste, Sudeste e Sul possuem trajetórias próprias.","Fronteiras culturais ultrapassam divisões administrativas."],"Evite listas de pratos sem contexto; explique território e formação.","Escolha uma região e monte mapa de ingredientes, técnicas e preparações.",["Brasil","regional","território"]),
  S("Mandioca e derivados","A mandioca é central em muitas tradições brasileiras. Farinha, goma, polvilho, tucupi e outros derivados resultam de processamentos diferentes e têm funções culinárias distintas.",["Mandioca mansa e brava exigem conhecimento adequado.","Polvilho doce e azedo comportam-se de formas distintas.","Farinha participa de acompanhamentos, farofas e pirões.","Tucupi é produto de processamento específico da mandioca."],"Questões podem relacionar derivado, processo e aplicação.","Compare tapioca, farinha e polvilho quanto à forma e ao uso.",["mandioca","tucupi","farinha"]),
  S("Pratos, técnicas e memória","Feijoadas, moquecas, vatapás, tacacás, arrozes, ensopados e assados variam muito entre regiões e comunidades. Receitas são registros vivos, sujeitos a adaptações e disputas de autoria.",["Estude técnica junto com história.","Evite declarar uma versão como única sem contexto.","Ingredientes locais influenciam variações.","Memória afetiva participa da valorização de pratos."],"Em prova, contextualize variações regionais.","Entreviste alguém sobre uma receita familiar e registre diferenças em relação a versões publicadas.",["pratos brasileiros","memória","técnica"])
 ]),
 D("Cozinhas Regionais Brasileiras","Aprofundamento em Amazônia, Nordeste, Centro-Oeste, Sudeste e Sul.","🗺️",[
  S("Cozinhas amazônicas","A região amazônica reúne peixes, mandioca e derivados, ervas, pimentas e frutas de grande diversidade. Práticas indígenas são fundamentais para compreender técnicas e ingredientes regionais.",["Tucupi, jambu e farinhas possuem usos específicos.","Peixes de água doce têm enorme importância.","Processamento tradicional da mandioca exige conhecimento técnico.","A diversidade vai muito além de poucos pratos conhecidos nacionalmente."],"Relacione ingrediente, povo, território e técnica.","Monte ficha de estudo de um ingrediente amazônico com origem e usos.",["Amazônia","jambu","peixes"]),
  S("Cozinhas nordestinas","O Nordeste reúne litoral, agreste, sertão e zonas de mata, formando cozinhas diversas. Mandioca, milho, coco, pescados, carnes, feijões, frutas e preparações de tabuleiro aparecem em combinações regionais.",["Bahia tem forte presença de tradições afro-brasileiras.","Sertão valoriza técnicas de conservação e ingredientes adaptados ao clima.","Cuscuz de milho possui múltiplas formas de consumo.","Cozinhas litorâneas diferem das sertanejas."],"Não trate o Nordeste como repertório homogêneo.","Compare um prato litorâneo e um sertanejo quanto a ingredientes e técnica.",["Nordeste","sertão","Bahia"]),
  S("Sudeste, Sul e Centro-Oeste","Essas regiões combinam tradições indígenas, africanas, europeias e migratórias em proporções diferentes. Tropeirismo, pecuária, agricultura, imigração e fronteiras moldaram pratos e modos de comer.",["Minas Gerais tem repertórios ligados a fazendas, queijos e conservação.","Sul recebeu diferentes fluxos migratórios e possui forte cultura de carnes e cereais.","Centro-Oeste dialoga com Cerrado e Pantanal.","São Paulo concentra repertórios migratórios e urbanos."],"Relacione formação econômica e geográfica aos hábitos alimentares.","Crie uma tabela comparativa entre três estados.",["Sudeste","Sul","Centro-Oeste"])
 ]),
 D("Cozinha Francesa","Técnicas clássicas, molhos, serviço e influência na formação profissional.","🥖",[
  S("Sistematização clássica e brigada","A cozinha francesa profissional foi importante na sistematização de técnicas, molhos, cortes e organização de brigada difundidos internacionalmente. O estudo atual deve reconhecer essa influência sem tratar o modelo como única referência possível.",["Escoffier ajudou a organizar estruturas clássicas.","Terminologia francesa permanece comum em escolas de cozinha.","Haute cuisine e cuisine bourgeoise representam contextos distintos.","Técnica deve ser estudada junto com história."],"Contextualize a influência francesa sem afirmar superioridade cultural.","Relacione cinco termos franceses a técnicas hoje usadas em diferentes cozinhas.",["França","Escoffier","brigada"]),
  S("Molhos e fundos clássicos","Sistemas clássicos organizaram molhos em famílias baseadas em fundos, roux, leite, tomate e emulsões. Na prática moderna, cozinhas adaptam essas estruturas, reduzindo peso e usando novas técnicas.",["Béchamel combina leite e roux.","Velouté parte de fundo claro e roux.","Espagnole historicamente usa fundo escuro e espessamento.","Hollandaise é emulsão quente."],"Reconheça bases, derivados e tipo de espessamento.","Monte árvore de um molho-base e dois derivados.",["molhos mãe","velouté","béchamel"]),
  S("Técnicas e preparações emblemáticas","Braseados, gratinados, pâtés, terrines, quiches, massas amanteigadas e técnicas de confeitaria compõem parte do repertório francês. O foco acadêmico deve ser entender princípio técnico e contexto.",["Gratinado cria crosta superficial por calor intenso.","Confit é cocção lenta em gordura em certos contextos.","Ragoûts combinam cocção prolongada e molho.","Pâtisserie possui técnicas específicas de precisão."],"Explique técnica antes de citar o nome de um prato.","Escolha uma preparação francesa e decomponha em técnicas transferíveis.",["França","técnicas","molhos"])
 ]),
 D("Cozinha Italiana e Mediterrânea","Massas, risotos, azeite, produtos regionais e lógica mediterrânea.","🍝",[
  S("Regionalidade da cozinha italiana","A Itália possui culinárias regionais marcadas por clima, agricultura, história e identidades locais. Norte e sul apresentam diferenças em gorduras, cereais, laticínios, massas e outros produtos, mas não há divisão simples que explique tudo.",["Produtos regionais são centrais na identidade.","Massas assumem formatos e molhos específicos.","Arroz e polenta têm grande importância no norte.","Azeite é relevante, mas manteiga também aparece em diversas regiões."],"Evite resumir cozinha italiana a massa e pizza.","Escolha duas regiões e compare ingredientes e técnicas.",["Itália","regional","massas"]),
  S("Massas frescas, secas e molhos","Massas podem ser feitas com diferentes trigos, ovos e hidratações. Formato, rugosidade e espessura influenciam retenção de molho. Cozinhar 'al dente' busca estrutura agradável, não massa crua.",["Água suficiente ajuda a dispersar amido.","Sal tempera a massa durante cocção.","Água do cozimento pode auxiliar emulsão do molho.","Molho deve ser ajustado ao formato."],"Explique por que finalizar a massa no molho melhora integração.","Teste o mesmo molho em formatos diferentes.",["massa","al dente","molho"]),
  S("Princípios mediterrâneos","Cozinhas ao redor do Mediterrâneo compartilham rotas, ingredientes e trocas históricas, mas mantêm grande diversidade cultural. Azeite, cereais, leguminosas, hortaliças, ervas e pescados aparecem em muitos repertórios.",["Mediterrâneo inclui Europa, Norte da África e Oriente Médio.","Não existe uma única 'cozinha mediterrânea'.","Ingredientes comuns têm técnicas e significados distintos.","Território e religião influenciam hábitos."],"Evite generalizações e reconheça múltiplas tradições.","Monte mapa de um ingrediente e seus diferentes usos no Mediterrâneo.",["Mediterrâneo","azeite","regional"])
 ]),
 D("Cozinhas Asiáticas","Panorama de tradições do Leste, Sudeste e Sul da Ásia.","🥢",[
  S("Diversidade das cozinhas asiáticas","Ásia reúne milhares de tradições culinárias. Arroz, massas, fermentados, especiarias, caldos e técnicas de cocção aparecem em muitas regiões, mas com lógicas próprias. Estudar por país e região é mais preciso que falar de uma cozinha asiática única.",["China possui múltiplas cozinhas regionais.","Japão enfatiza sazonalidade e técnicas próprias.","Sudeste Asiático trabalha grande diversidade de ervas e fermentados.","Sul da Ásia reúne repertórios complexos de especiarias."],"Evite usar 'oriental' como categoria técnica genérica.","Escolha três países e compare uma base aromática de cada um.",["Ásia","regionalidade","arroz"]),
  S("Umami, fermentados e caldos","Molhos fermentados, pastas, algas, cogumelos secos e caldos ricos em nucleotídeos aparecem em diferentes cozinhas e podem amplificar percepção de umami. Fermentação também contribui para conservação e complexidade aromática.",["Umami está ligado a glutamato e sinergias com nucleotídeos.","Missô, shoyu e fish sauce têm processos distintos.","Dashi é uma família de caldos, não uma receita única.","Fermentados precisam ser entendidos dentro de seu contexto cultural."],"Associe ingrediente, processo e função de sabor.","Compare dois condimentos fermentados e registre salinidade, aroma e uso.",["umami","fermentação","dashi"]),
  S("Wok, vapor e cocções rápidas","Wok permite grande transferência de calor e movimentação rápida; cozimento a vapor preserva umidade e é usado em diferentes preparações. Frituras e grelhados também variam amplamente entre regiões.",["Mise en place é essencial em cocções muito rápidas.","Pequenos cortes aceleram transferência de calor.","Molhos são adicionados em momentos específicos.","Equipamento e fonte de calor alteram resultado."],"Explique por que wok doméstico pode produzir resultado diferente do profissional.","Prepare vegetais em pequenos lotes e compare com panela lotada.",["wok","vapor","cocção"])
 ]),
 D("Cozinhas das Américas e Contemporânea","México, Andes, Estados Unidos e movimentos culinários atuais.","🌽",[
  S("Cozinhas mexicanas e nixtamalização","Milho, pimentas, feijões, ervas e técnicas ancestrais estruturam muitas cozinhas mexicanas. Nixtamalização trata milho em meio alcalino, alterando textura, sabor, funcionalidade e disponibilidade de nutrientes.",["Tortilla tradicional depende de masa nixtamalizada.","Pimentas variam em aroma, calor e uso.","Moles combinam múltiplos ingredientes e técnicas.","Cozinha mexicana vai muito além de estereótipos internacionais."],"Explique o propósito da nixtamalização.","Compare farinha de milho comum e masa quanto à aplicação.",["México","milho","nixtamalização"]),
  S("Andes e ingredientes americanos","Batatas, milho, quinoa, amaranto, pimentas, tomates e cacau são parte de sistemas alimentares americanos com longa história anterior à colonização europeia. Muitos se tornaram ingredientes globais depois das trocas colombianas.",["Batata possui enorme diversidade andina.","Quinoa tem usos diversos além de acompanhamento.","Tomate e cacau mudaram cozinhas em outros continentes.","Trocas alimentares foram ligadas a processos coloniais."],"Relacione circulação de ingredientes a transformações históricas globais.","Escolha um ingrediente americano e trace sua expansão.",["Andes","batata","quinoa"]),
  S("Cozinha contemporânea e inovação","Cozinha contemporânea pode combinar técnicas clássicas, ciência, design, sustentabilidade e repertórios locais. Inovar não é usar tecnologia pela novidade, mas criar coerência entre conceito, sabor, técnica, viabilidade e experiência.",["Técnica deve servir ao resultado sensorial.","Narrativa não compensa execução ruim.","Sustentabilidade pode integrar desenvolvimento de pratos.","Conhecer tradição ajuda a inovar com responsabilidade."],"Em respostas discursivas, diferencie inovação de simples novidade estética.","Redesenhe um prato tradicional mantendo sua identidade sensorial.",["contemporânea","inovação","criatividade"])
 ])
]
},
{
 id:"seguranca", number:"05", title:"Segurança, Qualidade e Sustentabilidade", icon:"🧼",
 description:"Microbiologia, boas práticas, APPCC, legislação, conservação, tecnologia e sustentabilidade.",
 theme:5,
 disciplines:[
 D("Higiene e Segurança dos Alimentos","Prevenção de perigos durante recebimento, armazenamento, preparo e serviço.","🧼",[
  S("Perigos biológicos, químicos e físicos","Perigo é agente ou condição com potencial de causar dano. Biológicos incluem microrganismos e toxinas; químicos incluem resíduos, produtos de limpeza e substâncias indevidas; físicos incluem objetos estranhos.",["Risco considera probabilidade e gravidade.","Controle começa na prevenção.","Um mesmo processo pode apresentar mais de um tipo de perigo.","Registros ajudam a demonstrar controle."],"Diferencie perigo e risco em exemplos práticos.","Observe uma cozinha e liste possíveis perigos em três etapas.",["perigos","segurança","risco"]),
  S("Contaminação cruzada","Contaminação cruzada ocorre quando microrganismos, alergênicos ou outros perigos passam de uma fonte para alimento, superfície ou utensílio. Separação física, higienização, fluxo e armazenamento ajudam a prevenir.",["Cru e pronto para consumo devem ser separados.","Mãos podem transferir contaminantes.","Tábuas e utensílios precisam ser higienizados.","Gotejamento em refrigeração é uma fonte de risco."],"Questões costumam apresentar cenários para identificar contaminação cruzada.","Desenhe uma geladeira correta, posicionando crus e prontos.",["contaminação cruzada","higiene","fluxo"]),
  S("Tempo, temperatura e cadeia fria","Microrganismos respondem às condições de tempo e temperatura. Recebimento, resfriamento, armazenamento, cocção, reaquecimento e manutenção precisam seguir procedimentos definidos e legislação aplicável.",["Termômetros devem ser adequados e higienizados.","Resfriamento precisa ocorrer de forma controlada.","Evite manter alimentos por períodos longos em condições favoráveis ao crescimento.","Registre desvios e ações corretivas."],"Use números somente de norma ou procedimento aplicável; o princípio geral é controlar exposição.","Crie uma planilha de registro para três etapas de temperatura.",["temperatura","cadeia fria","resfriamento"])
 ]),
 D("Microbiologia de Alimentos","Microrganismos, crescimento, deterioração e doenças transmitidas por alimentos.","🦠",[
  S("Bactérias, fungos, vírus e parasitas","Grupos de agentes apresentam características diferentes. Bactérias podem multiplicar-se no alimento; vírus precisam de células hospedeiras e são transmitidos por contaminação; fungos podem deteriorar produtos e alguns produzem toxinas; parasitas dependem de ciclos específicos.",["Nem todo microrganismo é patogênico.","Fermentações usam microrganismos benéficos.","Vírus não se multiplicam nos alimentos.","Algumas toxinas podem persistir mesmo após morte do microrganismo."],"Diferencie multiplicação no alimento e simples transporte do agente.","Monte tabela com grupo, exemplo de transmissão e medida preventiva.",["microbiologia","bactérias","vírus"]),
  S("Fatores de crescimento microbiano","Água disponível, temperatura, pH, oxigênio, nutrientes e tempo influenciam crescimento. Métodos de conservação atuam alterando uma ou mais dessas condições.",["Atividade de água não é o mesmo que teor de água.","Acidez reduz crescimento de muitos microrganismos.","Refrigeração desacelera, mas não esteriliza.","Combinar barreiras pode aumentar estabilidade."],"Associe método de conservação ao fator que ele modifica.","Compare sal, açúcar, frio e acidez como barreiras.",["crescimento microbiano","pH","atividade de água"]),
  S("Deterioração e doenças transmitidas por alimentos","Deterioração altera odor, sabor, cor ou textura, mas alimento perigoso nem sempre apresenta sinais visíveis. Doenças podem resultar de infecção, intoxicação ou mecanismos combinados.",["Aparência normal não garante segurança.","Sintomas dependem do agente e da dose.","Prevenção é mais eficaz que tentar detectar pelo aspecto.","Populações vulneráveis podem sofrer consequências mais graves."],"Não use cheiro como método de segurança.","Explique por que provar um alimento suspeito não é forma válida de avaliação.",["DTA","deterioração","patógenos"])
 ]),
 D("Boas Práticas de Fabricação","Rotinas padronizadas para ambiente, manipuladores e processos.","✅",[
  S("Higiene pessoal e conduta do manipulador","Mãos, uniforme, saúde, hábitos e comportamento afetam a segurança. Higienização correta das mãos deve ocorrer em momentos críticos e não pode ser substituída apenas por luvas.",["Unhas, adornos e feridas exigem controle.","Luvas podem contaminar se usadas de forma inadequada.","Uniforme deve estar limpo e apropriado.","Sintomas de doença precisam seguir procedimento da empresa."],"Questões frequentemente exploram uso indevido de luvas.","Liste cinco momentos em que lavar as mãos é obrigatório na rotina.",["BPF","manipulador","mãos"]),
  S("Limpeza e sanitização","Limpeza remove sujeira e resíduos; sanitização reduz microrganismos a níveis aceitáveis conforme o processo. Produtos exigem concentração, tempo de contato e uso indicados pelo fabricante.",["Sanitizante não funciona bem sobre sujeira pesada.","Enxágue depende do produto e procedimento.","Superfícies de contato precisam de rotina específica.","Nunca misture químicos sem orientação."],"Diferencie limpeza de sanitização.","Crie sequência padrão para uma bancada após produção.",["limpeza","sanitização","BPF"]),
  S("Recebimento, armazenamento e rastreabilidade","Controle começa na chegada: fornecedor, integridade, temperatura, validade e condições de transporte devem ser avaliados. Armazenamento exige identificação, proteção, rotação e separação adequadas.",["PVPS prioriza o que vence primeiro.","Produtos não devem ficar diretamente no piso.","Rótulos internos precisam permitir identificação.","Não conformidades devem ser registradas."],"Analise cenários de recebimento e determine aceitar ou rejeitar.","Monte checklist de recebimento com cinco critérios.",["recebimento","armazenamento","PVPS"])
 ]),
 D("APPCC e Controle de Qualidade","Análise de perigos, pontos críticos e monitoramento de processos.","📋",[
  S("Princípios do APPCC","APPCC é abordagem preventiva que identifica perigos significativos e define pontos em que controle é essencial. O sistema depende de pré-requisitos como Boas Práticas funcionando adequadamente.",["Identificar perigos e medidas de controle.","Determinar pontos críticos de controle.","Estabelecer limites, monitoramento e ações corretivas.","Verificar o sistema e manter registros."],"Decore a lógica dos princípios, mas saiba aplicá-la a um fluxo real.","Escolha uma preparação e desenhe as etapas antes de identificar perigos.",["APPCC","PCC","qualidade"]),
  S("Ponto crítico, limite e ação corretiva","PCC é etapa na qual controle é essencial para prevenir, eliminar ou reduzir um perigo significativo. Limite crítico separa condição aceitável de inaceitável. Se houver desvio, a ação corretiva deve tratar produto e causa.",["Monitoramento precisa ser mensurável e frequente o suficiente.","Limite crítico deve ter base técnica.","Ação corretiva não é simplesmente 'anotar o erro'.","Verificação confirma se o sistema funciona."],"Diferencie limite crítico, monitoramento e ação corretiva.","Crie um exemplo de PCC e escreva o que medir, quando e o que fazer no desvio.",["PCC","limite crítico","monitoramento"]),
  S("Indicadores e padronização da qualidade","Qualidade operacional envolve especificações de ingredientes, rendimento, porção, temperatura, apresentação, tempo e satisfação do cliente. Indicadores permitem identificar variação e priorizar melhorias.",["Padronização não elimina criatividade, mas reduz falhas repetitivas.","Ficha técnica é ferramenta de qualidade.","Indicadores precisam ter meta e frequência.","Dados devem orientar ação."],"Explique como uma ficha técnica contribui para qualidade e custo.","Escolha um indicador e determine fórmula, meta e frequência de análise.",["qualidade","indicadores","padronização"])
 ]),
 D("Legislação e Responsabilidade Profissional","Normas sanitárias, rotulagem e responsabilidade na operação.","⚖️",[
  S("Hierarquia e aplicação de normas","Operações de alimentos podem estar sujeitas a normas federais, estaduais e municipais, além de regras específicas do tipo de atividade. O profissional precisa verificar qual legislação vigente se aplica ao estabelecimento e localidade.",["Normas podem ser atualizadas.","Licenciamento depende do município e atividade.","Manual de Boas Práticas e POPs podem ser exigidos conforme regulamentação.","Documentação precisa refletir a prática real."],"Em concursos, confirme sempre a norma indicada no edital.","Crie uma lista de fontes oficiais que você deve consultar para sua cidade.",["legislação","vigilância sanitária","normas"]),
  S("Rotulagem e informação ao consumidor","Rótulos de alimentos embalados seguem requisitos de identificação, ingredientes, alergênicos e outras informações aplicáveis. Alegações e informações nutricionais precisam obedecer regras específicas.",["Lista de ingredientes segue critérios regulamentares.","Alergênicos exigem destaque conforme norma.","Validade e lote apoiam rastreabilidade.","Não faça alegações sem base permitida."],"Questões podem pedir diferença entre informação obrigatória e marketing.","Compare dois rótulos e identifique campos regulatórios.",["rotulagem","alergênicos","consumidor"]),
  S("Ética e responsabilidade","Responsabilidade profissional envolve segurança, transparência, respeito à equipe, honestidade com o consumidor e reconhecimento de autoria e tradição. Decisões técnicas têm impactos sociais e ambientais.",["Não ocultar riscos ao cliente.","Respeitar origem e contexto de receitas e saberes.","Evitar práticas discriminatórias na equipe.","Comunicar limitações e erros de forma responsável."],"Questões discursivas podem apresentar dilemas de operação.","Escreva como reagiria a um erro de produção descoberto antes do serviço.",["ética","responsabilidade","profissão"])
 ]),
 D("Sustentabilidade e Tecnologia de Alimentos","Redução de desperdício, conservação, inovação e uso responsável de recursos.","♻️",[
  S("Desperdício e aproveitamento integral","Reduzir desperdício começa em planejamento de compras, armazenamento, corte, porcionamento e produção. Aproveitamento integral usa partes comestíveis de forma segura, sem transformar qualquer resíduo em alimento automaticamente.",["Meça desperdício antes de propor soluções.","Aparas podem virar novas preparações quando próprias.","Porções excessivas também geram perdas.","Segurança e qualidade definem o que pode ser reaproveitado."],"Diferencie resíduo, sobra limpa e resto de prato.","Pese perdas de pré-preparo por uma semana e identifique maior causa.",["desperdício","aproveitamento","sustentabilidade"]),
  S("Sazonalidade, cadeia e escolhas de compra","Sazonalidade pode melhorar disponibilidade e qualidade e, em alguns casos, reduzir custos. Sustentabilidade também envolve origem, transporte, práticas de produção e relações de trabalho.",["Produto local não é automaticamente sustentável.","Compra responsável exige múltiplos critérios.","Cardápio sazonal precisa de flexibilidade.","Rastreabilidade melhora tomada de decisão."],"Evite respostas simplistas como 'local sempre é melhor'.","Escolha um ingrediente e compare duas possíveis cadeias de fornecimento.",["sazonalidade","compras","cadeia"]),
  S("Conservação e tecnologia de alimentos","Frio, calor, redução de atividade de água, acidificação, fermentação e embalagens são tecnologias de conservação. O objetivo é controlar deterioração e segurança preservando características desejadas.",["Congelamento reduz atividade microbiana, mas não esteriliza.","Secagem reduz água disponível.","Fermentação pode produzir ácidos e outros compostos conservantes.","Processos precisam de validação adequada."],"Associe método à barreira utilizada.","Monte tabela com método, princípio, vantagem e limitação.",["conservação","tecnologia","fermentação"])
 ])
]
},
{
 id:"gestao", number:"06", title:"Gestão, Eventos e Formação Acadêmica", icon:"📈",
 description:"Gestão de alimentos e bebidas, custos, cardápios, compras, eventos, empreendedorismo, estágio e TCC.",
 theme:6,
 disciplines:[
 D("Gestão de Alimentos e Bebidas","Operação, equipe, processos e indicadores de negócios gastronômicos.","📊",[
  S("Fluxo operacional e capacidade","Capacidade de uma operação depende de espaço, equipamentos, equipe, armazenamento e sequência de produção. Fluxo mal planejado gera cruzamentos, espera e retrabalho. O gestor deve mapear gargalos e alinhar produção ao volume de serviço.",["Capacidade não é apenas número de lugares.","Equipamento pode ser gargalo crítico.","Pré-preparo deve acompanhar previsão de demanda.","Fluxo seguro reduz cruzamentos entre áreas."],"Explique como gargalo afeta produtividade.","Desenhe o caminho de um prato do recebimento ao passe.",["gestão","fluxo","capacidade"]),
  S("Equipe, liderança e comunicação","Cozinhas funcionam sob pressão e dependem de comunicação clara. Liderança envolve distribuir responsabilidades, treinar, dar feedback, prevenir conflitos e manter padrões sem desrespeito.",["Briefings pré-serviço alinham prioridades.","Funções devem ser claras.","Feedback técnico deve ser específico.","Cultura de segurança depende da liderança."],"Diferencie autoridade operacional de comportamento abusivo.","Crie roteiro de briefing de cinco minutos antes do serviço.",["liderança","equipe","comunicação"]),
  S("Indicadores de desempenho","Vendas, ticket médio, CMV, desperdício, produtividade, tempo de serviço, satisfação e margem são exemplos de indicadores. Um número isolado diz pouco; é preciso meta, contexto e tendência.",["Indicador deve apoiar uma decisão.","Compare períodos equivalentes.","Analise causa antes de agir.","Combine métricas financeiras e operacionais."],"Saiba explicar por que CMV baixo demais também pode indicar problema de porção ou qualidade.","Escolha três indicadores e defina como seriam calculados.",["indicadores","gestão","A&B"])
 ]),
 D("Custos, Ficha Técnica e Precificação","Controle econômico das preparações e formação de preço.","💰",[
  S("Ficha técnica de preparação","A ficha técnica registra ingredientes, quantidades, rendimento, porção, modo de preparo e custos. Serve para padronizar produção, treinar equipe, prever compras e acompanhar mudanças de custo.",["Atualize preços de insumos periodicamente.","Rendimento real deve ser medido.","Custo por porção depende do rendimento.","Modo de preparo influencia perdas e consistência."],"Questões podem pedir vantagens da ficha técnica em gestão.","Preencha uma ficha técnica com peso bruto, líquido e custo.",["ficha técnica","custos","padronização"]),
  S("CMV e controle de estoque","Uma fórmula básica de CMV é estoque inicial + compras - estoque final. Para interpretar o indicador, compare-o às vendas e ao padrão do negócio. Inventários incorretos distorcem o resultado.",["Contagem física deve seguir rotina.","Perdas não registradas elevam custo real.","Compras excessivas imobilizam capital.","CMV percentual depende das vendas."],"Faça exercícios de CMV nominal e percentual.","Simule um período com estoque inicial, compras e final e analise o resultado.",["CMV","estoque","inventário"]),
  S("Precificação, margem e markup","Preço de venda precisa considerar custo de ingredientes, despesas, impostos, mão de obra, perdas, posicionamento e margem. Markup e margem são relações diferentes; usar um multiplicador sem conhecer a estrutura pode gerar preço inadequado.",["Custo de alimento é apenas parte do custo total.","Margem = resultado em relação ao preço de venda.","Markup relaciona preço ao custo por outro raciocínio.","Preço também depende de mercado e proposta de valor."],"Diferencie margem e markup em cálculos.","Calcule preço por dois métodos e compare com o mercado.",["precificação","margem","markup"])
 ]),
 D("Planejamento e Engenharia de Cardápio","Construção de menus viáveis e análise de desempenho de itens.","📝",[
  S("Estrutura e equilíbrio de cardápio","Cardápio comunica identidade e precisa considerar público, capacidade, equipamentos, estoque, sazonalidade, custo e coerência sensorial. Muitos itens podem aumentar complexidade e desperdício.",["Variedade deve ser administrável.","Compartilhar insumos entre pratos pode reduzir estoque.","Nome e descrição precisam ser claros.","Disponibilidade real deve corresponder ao que é oferecido."],"Explique por que cardápio amplo não significa necessariamente maior qualidade.","Analise um menu e identifique redundâncias de insumos e processos.",["cardápio","planejamento","menu"]),
  S("Engenharia de cardápio","Engenharia de cardápio combina popularidade e margem de contribuição para classificar itens e orientar decisões. A análise deve considerar dados de vendas confiáveis e contexto do negócio.",["Item popular e rentável merece destaque.","Item popular com baixa margem pode exigir ajuste.","Item rentável com baixa saída pode precisar de comunicação.","Item fraco em ambos os eixos pode ser revisto."],"Conheça a lógica de estrelas, cavalos de batalha, quebra-cabeças e cães, quando usada.","Pegue cinco itens fictícios e classifique por venda e margem.",["engenharia de cardápio","popularidade","margem"]),
  S("Sazonalidade e design do menu","Sazonalidade permite ajustar ingredientes conforme disponibilidade e pode reforçar identidade. Design do menu influencia leitura, destaque e percepção, mas não substitui qualidade e preço coerente.",["Destaques devem ser usados com intenção.","Descrições evocativas precisam ser verdadeiras.","Menu precisa ser legível.","Mudanças sazonais exigem planejamento de compras e equipe."],"Relacione design a decisão do consumidor sem tratar comportamento como automático.","Redesenhe uma seção de cardápio com hierarquia clara.",["menu","design","sazonalidade"])
 ]),
 D("Compras, Estoque e Fornecedores","Planejamento de abastecimento, inventário e relacionamento com fornecedores.","📦",[
  S("Previsão de compras e estoque mínimo","Compra deve considerar consumo histórico, previsão de vendas, estoque disponível, prazo de entrega e segurança. Estoque mínimo reduz risco de ruptura, mas excesso aumenta perdas e capital parado.",["Consumo médio ajuda a estimar necessidade.","Lead time do fornecedor influencia ponto de pedido.","Itens perecíveis pedem compras mais frequentes.","Previsão precisa ser revisada após eventos atípicos."],"Calcule necessidade de compra a partir de estoque e consumo previsto.","Monte ponto de pedido para um item de alta saída.",["compras","estoque mínimo","previsão"]),
  S("Inventário e rotação","Inventário compara estoque físico com registros. Diferenças podem vir de perda, erro de lançamento, porcionamento, furto ou desperdício. PVPS prioriza produtos que vencem primeiro.",["Contagens periódicas detectam desvios cedo.","Identificação e datação facilitam rotação.","Armazém organizado acelera inventário.","Unidades de medida precisam ser padronizadas."],"Diferencie PEPS e PVPS e saiba qual critério é mais útil quando validade é crítica.","Faça contagem de uma prateleira e compare com ficha de estoque.",["inventário","PVPS","estoque"]),
  S("Seleção e avaliação de fornecedores","Fornecedor deve ser avaliado por qualidade, regularidade, preço, prazo, condição sanitária, documentação e capacidade de atender especificações. Menor preço unitário nem sempre representa menor custo total.",["Crie especificação clara do produto.","Registre devoluções e não conformidades.","Compare prazo e frequência de entrega.","Mantenha alternativas para itens críticos."],"Questões de gestão podem apresentar conflito entre preço e confiabilidade.","Construa score simples com qualidade, prazo, preço e atendimento.",["fornecedores","compras","qualidade"])
 ]),
 D("Eventos e Catering","Planejamento, dimensionamento, logística e execução de eventos.","🎉",[
  S("Briefing e planejamento do evento","O briefing reúne número e perfil de convidados, data, duração, local, orçamento, restrições, estilo de serviço e infraestrutura. A partir dele são definidos cardápio, equipe, produção, transporte e montagem.",["Número de convidados sozinho não basta.","Tipo de serviço altera quantidade e equipe.","Local pode limitar energia, água e equipamentos.","Plano B é necessário para riscos relevantes."],"Identifique quais perguntas devem ser respondidas antes de criar o menu.","Monte briefing fictício para um jantar de 80 pessoas.",["eventos","briefing","catering"]),
  S("Dimensionamento de alimentos e bebidas","Estimativas consideram duração, horário, perfil, variedade, serviço e histórico. Quanto maior a variedade, menor pode ser o consumo individual de cada item. Margem de segurança deve ser racional, não desperdício automático.",["Use consumo real de eventos passados para ajustar previsões.","Canapés, buffet e empratado têm lógicas diferentes.","Bebidas dependem de clima, duração e público.","Restrições precisam ser contabilizadas."],"Resolva problemas de quantidade por pessoa e número de porções.","Calcule três cenários com margens de segurança diferentes.",["dimensionamento","porções","eventos"]),
  S("Logística, transporte e serviço","Catering exige transportar alimentos, utensílios e equipe mantendo segurança e qualidade. Cronograma precisa prever produção, resfriamento, embalagem, deslocamento, regeneração, montagem e desmontagem.",["Use caixas e equipamentos adequados à temperatura.","Etiquete volumes por setor ou estação.","Teste infraestrutura do local antes.","Defina responsável por conferência de saída e retorno."],"Questões podem pedir riscos de produzir fora da cozinha base.","Crie checklist de carga para um evento externo.",["logística","catering","serviço"])
 ]),
 D("Empreendedorismo Gastronômico","Modelo de negócio, proposta de valor e validação de ideias.","🚀",[
  S("Proposta de valor e público","Um negócio gastronômico precisa resolver uma necessidade ou entregar experiência desejada para um público específico. Produto, preço, canal, conveniência e marca devem ser coerentes com essa proposta.",["Público não deve ser definido apenas por idade.","Entenda ocasião de consumo e problema resolvido.","Diferenciação precisa ser percebida pelo cliente.","Proposta de valor deve ser testável."],"Diferencie produto de proposta de valor.","Entrevista cinco pessoas do público antes de definir o cardápio final.",["empreendedorismo","proposta de valor","público"]),
  S("Modelo de negócio e operação","Modelo de negócio conecta clientes, canais, receitas, custos, recursos, atividades e parceiros. Na Gastronomia, capacidade produtiva, perecibilidade e logística precisam entrar desde o início.",["Venda por delivery exige embalagem e tempo de transporte.","Loja física adiciona custos fixos e experiência de salão.","Produção sob encomenda muda estoque e previsão.","Parcerias podem reduzir necessidade de ativos próprios."],"Analise como canal de venda muda operação e custo.","Compare o mesmo produto em loja, delivery e evento.",["modelo de negócio","operação","canais"]),
  S("Validação, MVP e melhoria","Antes de investir alto, é possível testar produto, preço e demanda em pequena escala. MVP em Gastronomia deve continuar seguro e representativo da proposta, mesmo sendo simples.",["Teste hipótese específica.","Colete feedback estruturado.","Meça vendas, recompra e margem.","Ajuste com base em evidência, não apenas opinião."],"Explique por que 'lançar tudo pronto' aumenta risco.","Projete um teste de um fim de semana com métrica de sucesso.",["MVP","validação","negócio"])
 ]),
 D("Metodologia Científica, Estágio e TCC","Pesquisa acadêmica, registros de estágio e construção do trabalho final.","🎓",[
  S("Problema, objetivos e justificativa","Problema de pesquisa deve ser claro, delimitado e investigável. Objetivo geral expressa o principal resultado pretendido e objetivos específicos dividem o percurso em etapas. Justificativa explica relevância acadêmica, social ou profissional.",["Tema é mais amplo que problema.","Problema costuma ser formulado como pergunta.","Objetivos usam verbos coerentes com o método.","Justificativa não é apenas opinião pessoal."],"Identifique inconsistências entre problema e objetivos.","Transforme um tema amplo em pergunta delimitada por público, local ou processo.",["TCC","objetivos","problema"]),
  S("Metodologia, referências e fichamento","Metodologia descreve como dados serão obtidos e analisados. Pesquisa pode ser bibliográfica, documental, estudo de caso, levantamento, experimento ou combinação. Fichamento registra referência, ideias, dados e comentários com origem clara.",["Método precisa responder ao problema.","Fonte acadêmica deve ser avaliada por relevância e confiabilidade.","Registre página de citações durante a leitura.","Padronize referências conforme regra adotada pelo curso."],"Explique por que método não pode ser escolhido apenas por facilidade.","Faça fichamento de um artigo com objetivo, método, resultados e contribuição.",["metodologia","referências","fichamento"]),
  S("Estágio, relatório e desenvolvimento profissional","Estágio aproxima teoria e prática. Diário de campo ajuda a registrar tarefas, técnicas, problemas, aprendizagens e evolução. Relatório deve descrever contexto, atividades e análise crítica, evitando ser apenas lista de rotinas.",["Registre datas e horas com consistência.","Relacione experiências às disciplinas.","Identifique competências desenvolvidas.","Respeite confidencialidade da organização."],"Diferencie descrição de atividade e reflexão crítica.","Após cada turno, escreva uma situação, o que fez, resultado e o que melhoraria.",["estágio","relatório","carreira"])
 ])
]
}
];